language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install ghp-import
  - pip install flask
  - pip install flask-frozen
before script:
  - git config --global user.email 'your@email.com'
  - git config --global user.username 'username'
  - git remote rm origin
  - git remote add origin http://user:${GH_TOKEN}@github.com/user/repo.git
script: echo 'test'