language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install ghp-import
  - pip install flask
  - pip install Frozen-Flask
  - pip install Lektor
script: 
  - echo 'test'
  - lektor build -O build
  - ghp-import -m "Build static site" build
after_success:
  - bash deploy.sh