language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install ghp-import
  - pip install flask
  - pip install Frozen-Flask
  - pip install Lektor
before script:
  - git config --global user.email 'your@email.com'
  - git config --global user.username '5j4'
  - git remote rm origin
  - git remote add origin http://user:${GH_TOKEN}@github.com/user/travis-deploy-demo.git
script: 
  - echo 'test'
  - lektor build -O build
  - ghp-import -m "Build static site" build
  - git branch
  - git push -fq "https://${GH_TOKEN}@github.com/travis-deploy-demo.git" gh-pages:gh-pages > /dev/null 2>&1
  # - git push origin ${GITHUB_PAGES_BRANCH}
after success:
  - bash deploy.sh